### ISSUE TITLE
Version number conflict when using --dev

### ISSUE THREAD

**Issue by ajashton** [mapbox/npm-internal#15]
I tried running `npm-internal publish --dev` but  got the following output:

```
dev publish: <my-package>-

<my-package>-6.2.1 already exists.
Please either increment the version number in package.json to remove the conflict and try again.
Or for a dev package use --dev
```

My understanding of `--dev` is that it should be appending a hash to the version number to avoid duplicate version problems. Is there a bug or am I misunderstanding?

**Comment by jfirebaugh** [comment]
:+1:, I think this should work too.

**Comment by jfirebaugh** [comment]
Turned out I had an old version of npm-internal installed. Upgrading fixed this.

**Comment by karenzshea** [comment]
Ran into this today too - on linux machines the command must be `git rev-parse HEAD` rather than [`git rev-parse head`](https://github.com/mapbox/npm-internal/blob/5cb9c238e37d3edfa3b01771a6fbbb49715275da/index.js#L49)

This might be irrelevant eventually though with https://github.com/mapbox/npm-internal/issues/18

**Comment by ianshward** [comment]
Is this fixed now via https://github.com/mapbox/npm-internal/pull/19 ?

**Comment by freenerd** [comment]
Not sure where the initial problem was, @ajashton did correctly assess that there should be no conflict since the gitsha is attached. Also #18 and #19 might have helped. Closing for now, re-open if it happens again.

**Comment by ian29** [comment]
im hitting the same problem, but because this time because `--dev` first gets it's gitsha from `git describe --tags` rather than just reading package.json: https://github.com/mapbox/npm-internal/blob/master/index.js#L48

i think the ideal behavior would be to always always read the package.json version and never tags (assuming it's unlikely that if you're publishing a dev pkg that you've incremented the tag). 

i can do a quickie PR that just removes https://github.com/mapbox/npm-internal/blob/master/index.js#L48

**Comment by ian29** [comment]
blorp. i misread the OP. my issue is slightly different. i'll open a fresh ticket.
